package com.example.cccc.entity

data class ExamItem(val id: Int, val questions: List<String>)
data class ExamAnswers(val answers: Map<String, String>)
data class ExamResult(val success: Boolean, val score: Int)
data class PaymentItem(val id: Int, val amount: Double, val date: String)
data class ReviewRequest(val rating: Int, val comment: String)
data class ReviewResponse(val success: Boolean)
data class StudentItem(val id: Int, val name: String)
data class AddStudentRequest(val studentId: Int)
data class AddStudentResponse(val success: Boolean)
data class CourseStats(val studentsCount: Int, val averageScore: Double)
data class CreateCourseForm(val fields: List<String>)
data class CreateCourseRequest(val title: String, val description: String)
data class TeacherDashboard(val coursesCount: Int, val studentsCount: Int)
data class TeacherProfile(val name: String, val email: String)
data class TeacherProfileUpdate(val name: String, val email: String)
data class MaterialUploadRequest(val fileUrl: String)
data class MaterialUploadResponse(val success: Boolean)
data class TokenRequest(val username: String, val password: String)
data class TokenResponse(val access: String, val refresh: String)
data class RefreshTokenRequest(val refresh: String)
